name: Build and Release Binary

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y build-essential

      - name: Compile the program (Linux/macOS)
        run: |
          mkdir build
          make all
          ls -lh ./build/erosDB

      - name: Upload artifact for release
        uses: actions/upload-artifact@v3
        with:
          name: eros_database-${{ matrix.os }}
          path: eros_database

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: eros_database-ubuntu-latest

      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: eros_database-macos-latest

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }} # The Git tag that was pushed
          release_name: Release ${{ github.ref }}
          body: |
            Binary release for version ${{ github.ref }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_PAT }}

      - name: Upload binaries to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: eros_database-ubuntu-latest
          asset_name: eros_database-linux
          asset_content_type: application/octet-stream

      - name: Upload macOS binary to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: eros_database-macos-latest
          asset_name: eros_database-macos
          asset_content_type: application/octet-stream
