name: Build and Release Binary

on:
  push:
    tags:
      - '*'  # Triggers on any tag

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y build-essential

      - name: Compile the program (Linux/macOS)
        run: |
          mkdir -p build
          make all
          ls -lh ./build/erosDB

      - name: Rename and upload artifact
        run: mv build/erosDB erosDB-${{ matrix.os }}  # Rename the artifact to match the OS

      - name: Upload artifact for release
        uses: actions/upload-artifact@v3
        with:
          name: erosDB-${{ matrix.os }}
          path: erosDB-${{ matrix.os }}  # Ensure the correct file path

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  # Add this step to ensure the repo is cloned
        uses: actions/checkout@v3

      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: erosDB-ubuntu-latest

      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: erosDB-macos-latest

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Create GitHub Release with GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN, or your PAT in secrets if needed
        run: |
          gh release create ${{ github.ref }} erosDB-ubuntu-latest#erosDB-linux erosDB-macos-latest#erosDB-macos --title "Release ${{ github.ref }}" --notes "Automated release for ${{ github.ref }}"
